trigger:
- develop

pool:
  vmImage: ubuntu-latest

steps:
- task: Npm@1
  displayName: 'npm install'
  inputs:
    verbose: false
    customEndpoint: fontawesome

- task: gulp@0
  displayName: 'Run gulp task'
  inputs:
    targets: export

- task: ArchiveFiles@2
  displayName: 'Archive files'
  inputs:
    rootFolderOrFile: export
    includeRootFolder: false
    archiveFile: '$(Build.ArtifactStagingDirectory)/ds.zip'

- task: PublishBuildArtifacts@1
  displayName: 'Publish Artifact: drop'